const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";
const ONLINE_USERS = "ONLINE_USERS";
const USER_ONLINE = "USER_ONLINE";
const MESSAGE_DELIVERED = "MESSAGE_DELIVERED";
const MESSAGE_READ = "MESSAGE_READ";
const CALL_USER = "CALL_USER";
const RECEIVE_CALL = "RECEIVE_CALL";
const ANSWER_CALL = "ANSWER_CALL";
const CALL_ANSWERED = "CALL_ANSWERED";
const SEND_ICECANDIDATE = "SEND_ICECANDIDATE";
const RECEIVE_ICECANDIDATE = "RECEIVE_ICECANDIDATE";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  USER_ONLINE,
  MESSAGE_DELIVERED,
  MESSAGE_READ,
  CALL_USER,
  RECEIVE_CALL,
  ANSWER_CALL,
  CALL_ANSWERED,
  SEND_ICECANDIDATE,
  RECEIVE_ICECANDIDATE
};
